# Generated by Django 5.2.1 on 2025-06-01 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='image',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('TOP', 'Top Wear (Shirts, T-Shirts, etc.)'), ('BOTTOM', 'Bottom Wear (Pants, Jeans, Skirts)'), ('DRESS', 'Dresses'), ('OUTERWEAR', 'Outerwear (Jackets, Coats)'), ('FOOTWEAR', 'Footwear'), ('ACCESSORY', 'Accessory')], default='TOP', max_length=20),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='image_2d',
            field=models.ImageField(default=django.utils.timezone.now, help_text='2D image for display in lists/galleries', upload_to='clothing_images/2d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='model_3d_file',
            field=models.FileField(blank=True, help_text='3D model file (e.g., .glb, .obj)', null=True, upload_to='clothing_models/3d/'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='sizes_available',
            field=models.CharField(blank=True, help_text='e.g., S, M, L, XL or 30, 32, 34', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='texture_file',
            field=models.FileField(blank=True, help_text='Texture file for the 3D model, if separate', null=True, upload_to='clothing_models/textures/'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
