# Generated by Django 5.2.1 on 2025-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_title_clothingitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='target_audience',
            field=models.CharField(choices=[('MEN', "Men's"), ('WOMEN', "Women's"), ('KIDS', "Kids'"), ('UNISEX', 'Unisex')], db_index=True, default='UNISEX', max_length=10),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('TOP', 'Top Wear (Shirts, T-Shirts, etc.)'), ('BOTTOM', 'Bottom Wear (Pants, Jeans, Skirts)'), ('DRESS', 'Dresses'), ('OUTERWEAR', 'Outerwear (Jackets, Coats)'), ('FOOTWEAR', 'Footwear'), ('ACCESSORY', 'Accessory')], db_index=True, default='TOP', max_length=20),
        ),
    ]
